Improve handling of surrogate gradient functions
jstapmanns/nest-simulator pull request #38
Opened 2023-11-12 22:23 UTC by JesusEV

I created a PR for this change for further discussion

2023-11-13 16:04 UTC, akorgor commented on nestkernel/eprop_archiving_node.h
> +// C++ includes:
```suggestion
// C++
```
In the other files we do not repeat "include" in the title of a new list of includes. It's clear that its a list of includes, since the lines start with `#include`

2023-11-13 16:07 UTC, akorgor commented
Nice change! Looks overall good to me

2023-11-14 07:47 UTC, JesusEV commented
Hi @helplesser, I'm looking for your input on this PR, which aims to streamline the introduction of new surrogate gradient functions. Do you feel the proposed changes are an effective approach for achieving this?  your thoughts would be valuable as I'm considering implementing a similar solution for introducing new optimization functions in the synapses. Your feedback would be much appreciated!

2023-11-14 08:01 UTC, akorgor commented on models/eprop_iaf_psc_delta.cpp
> +    {
Could this be maybe rather solved with `nest::names`?  Maybe @heplesser can advise here?

2023-11-14 13:58 UTC, heplesser requested changes
@JesusEV In principle this is a nice approach and not too far from what I am planning for the optimizers. The main problem I see with the solution is that you had to create the same code twice, once for the plain delta and once for the adapting one. 

A solution would be to turn the gradient functions into templated plain functions with the eprop neuron model as template argument, something like

```c++
template < typename NodeType >
double
surrogate_gradient_piecewise_linear( const NodeType& n )
{
  ...
  return ...;
}
```

Any class allowing use of this function should declare it at `friend`, so the function can directly access the private members via `n`.

The list of gradient functions could then be managed by `model_manager` in similar ways as it manages the node models.

The approach for the optimizers would be similar, but there we should have a class for each optimizer, so that all parameters and variables that belong to the optimizer (not the node or synapse) can be stored in the optimizer.

See also some minor comments.

2023-11-14 13:58 UTC, heplesser commented on models/eprop_iaf_psc_delta.cpp
> +      if ( !first )
```suggestion
      if ( not first )
```

2023-11-14 13:58 UTC, heplesser commented on models/eprop_iaf_psc_delta.cpp
>    const double v_m = S_.r_ > 0 ? 0.0 : S_.y3_;
Usually ReLU is zero or positive, but here the meaning is that it should be zero or negative, right?

```suggestion
  const double v_m = std::min( 0, S_.y3_ );
```

2023-11-14 15:56 UTC, JesusEV commented
> @JesusEV In principle this is a nice approach and not too far from what I am planning for the optimizers. The main problem I see with the solution is that you had to create the same code twice, once for the plain delta and once for the adapting one.
> 
> A solution would be to turn the gradient functions into templated plain functions with the eprop neuron model as template argument, something like
> 
> ```c++
> template < typename NodeType >
> double
> surrogate_gradient_piecewise_linear( const NodeType& n )
> {
>   ...
>   return ...;
> }
> ```
> 
> Any class allowing use of this function should declare it at `friend`, so the function can directly access the private members via `n`.
> 
> The list of gradient functions could then be managed by `model_manager` in similar ways as it manages the node models.
> 
> The approach for the optimizers would be similar, but there we should have a class for each optimizer, so that all parameters and variables that belong to the optimizer (not the node or synapse) can be stored in the optimizer.
> 
> See also some minor comments.

@heplesser I really like what you are saying about classes for optimizers. Surrogate gradients, by the way, may also have a few parameters of their own (for example the gamma parameter in the case of piecewise_linear_surrogate_gradient), could this aspect make surrogate gradients also worthy of being promoted to classes?

2023-11-14 16:01 UTC, JesusEV commented on models/eprop_iaf_psc_delta.cpp
>    const double v_m = S_.r_ > 0 ? 0.0 : S_.y3_;
I see what you mean. However, the condition is really that S_.r_, which corresponds to the remaining steps of the refractory period, is zero so that the surrogate gradient can potentially be different from zero.

2023-11-14 16:40 UTC, JesusEV commented
@heplesser By the way, both surrogate gradients and optimizers have a much broader scope than just e-prop, their application is relevant for large portion of learning rules in spiking neuron networks, including the biologically reasonable ones [arXiv:2109.12894]. Therefore, it seems to me that the suggestion of making them available to more models is an extremely interesting proposal!

2023-11-14 20:54 UTC, heplesser commented
> @heplesser I really like what you are saying about classes for optimizers. Surrogate gradients, by the way, may also have a few parameters of their own (for example the gamma parameter in the case of piecewise_linear_surrogate_gradient), could this aspect make surrogate gradients also worthy of being promoted to classes?

Yes, definitely.

2023-11-14 20:54 UTC, heplesser commented on models/eprop_iaf_psc_delta.cpp
>    const double v_m = S_.r_ > 0 ? 0.0 : S_.y3_;
Sorry, I got that completely wrong!

2023-11-14 20:58 UTC, JesusEV commented on models/eprop_iaf_psc_delta.cpp
>    const double v_m = S_.r_ > 0 ? 0.0 : S_.y3_;
Yes, that in particular made me think that probably that function is not as straightforwardly understandable as it could/should be, I am considering:
`
double
nest::eprop_iaf_psc_delta_adapt::compute_piecewise_linear_derivative()
{
  if ( S_.r_ > 0 )
  { 
    return 0.0;
  }

  return P_.gamma_ * std::max( 0.0, 1.0 - std::fabs( ( S_.y3 - S_.adapting_threshold_ ) / P_.V_th_ ) ) / P_.V_th_;
}
`

2023-11-14 23:22 UTC, heplesser commented on models/eprop_iaf_psc_delta.cpp
>    const double v_m = S_.r_ > 0 ? 0.0 : S_.y3_;
Yes, I think that is much clearer.

2023-11-27 13:39 UTC, closed without merging